This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./main_horizon.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main_horizon.acn....done (108 entries accepted, 0 rejected).
Sorting entries....done (776 comparisons).
Generating output file main_horizon.acr....done (123 lines written, 0 warnings).
Output written in main_horizon.acr.
Transcript written in main_horizon.alg.
