using Lux
using SafeTensors
using ComponentArrays
using Random
using Statistics

include("../src/models/totalsegmentator.jl")
include("../src/utils/weight_loading.jl")

function verify_real_logits()
    println("=== Verifying Real Data Logits ===")
    
    # Path to logits generated by Python
    path = "verification_data/logits_ts_ct.safetensors"
    if !isfile(path)
        println("File not found: $path")
        return
    end
    
    tensors = SafeTensors.load_safetensors(path)
    # Python input: (C, D, H, W) -> (1, 112, 112, 128)
    x_pt = tensors["input"]
    # Python logits: (Classes, D, H, W) -> (118, 112, 112, 128)
    # Wait, logits shape in log was (118, 112, 112, 128) (C, D, H, W) relative to python.
    # Actually nnU-Net outputs (Batch, Classes, D, H, W) usually? No, the script squeezed batch.
    y_pt = tensors["logits"]
    
    println("Python Input Shape: ", size(x_pt))
    println("Python Logits Shape: ", size(y_pt))
    
    # Permute Input to Lux: (W, H, D, C, N)
    # Python (C, D, H, W) -> Lux (W, H, D, C, 1)
    x_lux = permutedims(x_pt, (4, 3, 2, 1))
    x_lux = reshape(x_lux, size(x_lux)..., 1)
    
    println("Lux Input Shape: ", size(x_lux))
    
    # Permute Reference Logits to Lux: (W, H, D, C, N)
    y_ref = permutedims(y_pt, (4, 3, 2, 1))
    y_ref = reshape(y_ref, size(y_ref)..., 1)
    
    # Setup Model
    model = TotalSegmentator(118)
    weights_path = "verification_data/totalseg_weights.safetensors"
    
    println("Loading weights from $weights_path")
    # This uses my current loading logic (which has FLIPPING)
    ps = load_totalseg_weights(model, weights_path)
    
    rng = Random.default_rng()
    _, st = Lux.setup(rng, model)
    st = Lux.testmode(st)
    
    println("Running Lux Inference...")
    y_lux, _ = model(x_lux, ps, st)
    
    println("Lux Output Shape: ", size(y_lux))
    
    # Compare
    diff = abs.(y_lux .- y_ref)
    max_diff = maximum(diff)
    mean_diff = mean(diff)
    
    println("Max Difference: ", max_diff)
    println("Mean Difference: ", mean_diff)
    
    if max_diff > 1.0
        println("FAILURE: Large mismatch.")
    else
        println("SUCCESS: Match.")
    end
    
    # Check Segmentation (Argmax)
    println("\nChecking Segmentation Matching...")
    
    # Python Argmax (0-based)
    # y_ref is (W, H, D, C, 1)
    # Find max along C (dim 4)
    # Julia argmax returns indices into appropriate dimension or CartesianIndex.
    # Base.argmax on array dims=4 returns CartesianIndices.
    
    # Extract logits indices
    function get_labels(logits)
        # dims=4
        am = dropdims(argmax(logits, dims=4), dims=4) # CartesianIndex
        # Extract class index (4th component of CartesianIndex?)
        # CartesianIndex(w, h, d, c, n). We want c.
        return map(x -> x[4], am)
    end
    
    labels_lux = get_labels(y_lux)
    labels_ref = get_labels(y_ref) # Note: this is actually computing argmax on Python logits IN JULIA.
    # This verifies if the LOGITS imply the same classes.
    # Python's saved nifti used numpy.argmax. Julia behaves same.
    
    mismatch_count = count(labels_lux .!= labels_ref)
    total_voxels = length(labels_lux)
    prob_mismatch = mismatch_count / total_voxels
    
    println("Use labels (1-based Julia inference): ", labels_lux[1:5])
    println("Ref labels (1-based Ref inference): ", labels_ref[1:5]) 
    
    println("Segmentation Mismatch Fraction: ", prob_mismatch)
    
    if prob_mismatch < 0.01
        println("SUCCESS: Segmentation matches (>99%)")
    else
        println("WARNING: High mismatch in segmentation.")
    end
end

verify_real_logits()
